import "./globals.css";
import type { Metadata } from "next";
import { Lato } from "next/font/google";
import localFont from "next/font/local";
import NavBar from "./NavBar";
import AuthProvider from "./auth/Provider";

const lato = Lato({ subsets: ["latin"], weight: ["400", "700"] });
const tenorite = localFont({
  src: "../public/fonts/29595851800.ttf",
  variable: "--font-tenorite",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className={tenorite.variable}>
        <AuthProvider>
          <NavBar />
          <main className="p-5">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
